# DO NOT EDIT - generated by scripts/generate-nix-compose.ts
{ lib, pkgs, workspaceDir, composeEnvFile }:

{
  # Containers
  virtualisation.oci-containers.containers."meristem-apisix" = {
    image = "apache/apisix:3.9.1-debian";
    volumes = [
      "${workspaceDir}/ops/apisix/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro"
      "${workspaceDir}/ops/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=bash -c 'exec 3<>/dev/tcp/127.0.0.1/9080'"
      "--health-interval=5s"
      "--health-retries=20"
      "--health-timeout=3s"
      "--network=host"
    ];
  };
  systemd.services."docker-meristem-apisix" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-meristem-root.target"
    ];
    wantedBy = [
      "docker-compose-meristem-root.target"
    ];
  };

}
