# DO NOT EDIT - generated by scripts/generate-nix-compose.ts
{ lib, pkgs, workspaceDir }:

{
  # Containers
  virtualisation.oci-containers.containers."meristem-apisix" = {
    image = "apache/apisix:3.9.1-debian";
    volumes = [
      "${workspaceDir}/ops/apisix/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro"
      "${workspaceDir}/ops/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro"
    ];
    ports = [
      "9080:9080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--health-cmd=curl -fsS http://127.0.0.1:9080/api/v0/health >/dev/null || exit 1"
      "--health-interval=5s"
      "--health-retries=20"
      "--health-timeout=3s"
      "--network-alias=apisix"
      "--network=meristem_default"
    ];
  };
  systemd.services."docker-meristem-apisix" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-meristem_default.service"
    ];
    requires = [
      "docker-network-meristem_default.service"
    ];
    partOf = [
      "docker-compose-meristem-root.target"
    ];
    wantedBy = [
      "docker-compose-meristem-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-meristem_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f meristem_default";
    };
    script = ''
      docker network inspect meristem_default || docker network create meristem_default
    '';
    partOf = [ "docker-compose-meristem-root.target" ];
    wantedBy = [ "docker-compose-meristem-root.target" ];
  };

}
