# DO NOT EDIT - generated by scripts/generate-nix-compose.ts
{ lib, pkgs, workspaceDir, composeEnvFile }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."meristem-nats" = {
    image = "nats:2-alpine";
    volumes = [
      "${workspaceDir}/ops/nats/nats.conf:/etc/nats/nats.conf:ro"
    ];
    ports = [
      "4222:4222/tcp"
      "4223:4223/tcp"
      "8222:8222/tcp"
    ];
    cmd = [ "-c" "/etc/nats/nats.conf" ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"wget\", \"-q\", \"-O\", \"-\", \"http://127.0.0.1:8222/healthz\"]"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=3s"
      "--network-alias=nats"
      "--network=meristem_default"
    ];
  };
  systemd.services."docker-meristem-nats" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-meristem_default.service"
    ];
    requires = [
      "docker-network-meristem_default.service"
    ];
    partOf = [
      "docker-compose-meristem-root.target"
    ];
    wantedBy = [
      "docker-compose-meristem-root.target"
    ];
  };
  virtualisation.oci-containers.containers."meristem-postgres" = {
    image = "postgres:16-alpine";
    environmentFiles = [ composeEnvFile ];
    ports = [
      "55432:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=sh -c 'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"'"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=3s"
      "--network-alias=postgres"
      "--network=meristem_default"
    ];
  };
  systemd.services."docker-meristem-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-meristem_default.service"
    ];
    requires = [
      "docker-network-meristem_default.service"
    ];
    partOf = [
      "docker-compose-meristem-root.target"
    ];
    wantedBy = [
      "docker-compose-meristem-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-meristem_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f meristem_default";
    };
    script = ''
      docker network inspect meristem_default || docker network create meristem_default
    '';
    partOf = [ "docker-compose-meristem-root.target" ];
    wantedBy = [ "docker-compose-meristem-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-meristem-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
