# DO NOT EDIT - generated by scripts/generate-nix-compose.ts
{ lib, pkgs, workspaceDir }:

{
  # Containers
  virtualisation.oci-containers.containers."meristem-opensearch" = {
    image = "opensearchproject/opensearch:2-alpine";
    environment = {
      "OPENSEARCH_INITIAL_ADMIN_PASSWORD" = "Meristem0pensearch!";
      "discovery.type" = "single-node";
      "plugins.security.disabled" = "true";
    };
    ports = [
      "9200:9200/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=curl -s http://localhost:9200/_cluster/health | grep -E 'green|yellow|red' || exit 1"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=3s"
      "--network-alias=opensearch"
      "--network=meristem_default"
    ];
  };
  systemd.services."docker-meristem-opensearch" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-meristem_default.service"
    ];
    requires = [
      "docker-network-meristem_default.service"
    ];
    partOf = [
      "docker-compose-meristem-root.target"
    ];
    wantedBy = [
      "docker-compose-meristem-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-meristem_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f meristem_default";
    };
    script = ''
      docker network inspect meristem_default || docker network create meristem_default
    '';
    partOf = [ "docker-compose-meristem-root.target" ];
    wantedBy = [ "docker-compose-meristem-root.target" ];
  };

}
