# DO NOT EDIT - generated by scripts/generate-nix-compose.ts
{ lib, pkgs, workspaceDir }:

{
  # Containers
  virtualisation.oci-containers.containers."meristem-redis" = {
    image = "redis:7-alpine";
    ports = [
      "6379:6379/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"redis-cli\", \"ping\"]"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=3s"
      "--network-alias=redis"
      "--network=meristem_default"
    ];
  };
  systemd.services."docker-meristem-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-meristem_default.service"
    ];
    requires = [
      "docker-network-meristem_default.service"
    ];
    partOf = [
      "docker-compose-meristem-root.target"
    ];
    wantedBy = [
      "docker-compose-meristem-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-meristem_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f meristem_default";
    };
    script = ''
      docker network inspect meristem_default || docker network create meristem_default
    '';
    partOf = [ "docker-compose-meristem-root.target" ];
    wantedBy = [ "docker-compose-meristem-root.target" ];
  };

}
