import { err, ok, type Result } from '../../../packages/common/src/result.ts'
import {
  decodeMDeployDesiredStateDocumentV01,
  type MDeployDesiredStateDocumentV01FromSchema,
  type MDeployDigestFromSchema,
  type MDeployDriftReportV01FromSchema,
  type MDeployInfrastructureTopologyV01FromSchema,
  type MDeployRuntimeHealthV01FromSchema,
  validateMDeployInfrastructureTopologyV01
} from '../../../packages/contracts/src/index.ts'
import type {
  MDeployDriverError,
  MDeployOpenTofuModuleInput,
  MDeployQuadletRender,
  MDeployRenderedFile
} from './infrastructure-driver-types.ts'

const rootlessUnitDirectory = '%h/.config/containers/systemd' as const
const secretBearingTerms = ['password', 'token', 'secret', 'key', 'credential'] as const

type SecretIdentity = {
  readonly provider: string
  readonly keyPath: string
  readonly version?: number | undefined
}

/** 将中立拓扑转换为稳定的 OpenTofu 模块变量文档，具体 provider 绑定保持在模块外。 */
export function renderOpenTofuModuleInput(
  input: unknown
): Result<MDeployOpenTofuModuleInput, MDeployDriverError> {
  const decoded = validateMDeployInfrastructureTopologyV01(input)
  if (!decoded.ok) return decoded
  if (!isProductionValidationFixture(decoded.value)) {
    return err({
      code: 'topology_invalid',
      message: 'validation topology requires 3 control-state, 3 search, and 2 leaf Podman nodes'
    })
  }
  return ok({
    schemaVersion: 'mdeploy.opentofu-module-input@0.1.0',
    topology: decoded.value
  })
}

/** 只根据已验证 desired-state 生成生产 Podman Quadlet 与 user-systemd 单元，不执行 I/O。 */
export function renderPodmanQuadlets(
  input: unknown
): Result<MDeployQuadletRender, MDeployDriverError> {
  const desiredState = validateDesiredStateForRender(input, 'podman')
  if (!desiredState.ok) return desiredState

  const files: MDeployRenderedFile[] = []
  for (const service of stableServices(desiredState.value)) {
    const rendered = renderQuadletService(service)
    if (!rendered.ok) return rendered
    files.push(rendered.value)
  }
  files.push({ path: 'meristem.target', content: renderMeristemTarget(desiredState.value) })
  return ok({
    runtimeClass: 'production',
    runtimeDriver: 'podman',
    unitManager: 'quadlet-systemd',
    rootlessUnitDirectory,
    files
  })
}

/** Docker Compose 输出仅用于兼容性验证，不能作为生产就绪或 HA 证明。 */
export function renderComposeCompatibility(input: unknown): Result<string, MDeployDriverError> {
  const desiredState = validateDesiredStateForRender(input, 'docker')
  if (!desiredState.ok) return desiredState

  const services: string[] = []
  const externalSecrets = new Map<string, string>()
  for (const service of stableServices(desiredState.value)) {
    const rendered = renderComposeService(service, externalSecrets)
    if (!rendered.ok) return rendered
    services.push(rendered.value)
  }
  const secretBlock = [...externalSecrets.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .flatMap(([name, externalName]) => [
      `  ${name}:`,
      `    name: ${yamlQuote(externalName)}`,
      '    external: true'
    ])

  return ok(
    [
      '# Generated by M-Deploy; compatibility-only, never a production runtime manifest.',
      'name: meristem-compatibility-only',
      'services:',
      ...services,
      ...(secretBlock.length === 0 ? [] : ['secrets:', ...secretBlock]),
      ''
    ].join('\n')
  )
}

/** 将观察到的本地运行条件映射为版本化 runtime-health 事实。 */
export function deriveMDeployRuntimeHealth(input: {
  readonly agentId: string
  readonly hostId: string
  readonly runtimeAvailable: boolean
  readonly unitManagerAvailable: boolean
  readonly immutableImageVerified: boolean
  readonly appliedImageDigest?: MDeployDigestFromSchema
  readonly checkedAt: string
}): MDeployRuntimeHealthV01FromSchema {
  const health = !input.runtimeAvailable
    ? 'unhealthy'
    : input.unitManagerAvailable && input.immutableImageVerified
      ? 'healthy'
      : 'degraded'
  return {
    schemaVersion: 'mdeploy.runtime-health@0.1.0',
    agentId: input.agentId,
    hostId: input.hostId,
    runtime: {
      schemaVersion: 'mdeploy.runtime-driver-selection@0.1.0',
      runtimeClass: 'production',
      runtimeDriver: 'podman',
      unitManager: 'quadlet-systemd',
      iacDriver: 'opentofu',
      selectedAt: input.checkedAt,
      selectedBy: 'm-deploy-agent'
    },
    health,
    checkedAt: input.checkedAt,
    checks: {
      runtimeAvailable: input.runtimeAvailable,
      unitManagerAvailable: input.unitManagerAvailable,
      immutableImageVerified: input.immutableImageVerified
    },
    ...(input.appliedImageDigest ? { appliedImageDigest: input.appliedImageDigest } : {})
  }
}

/** 以不可变 digest 比较期望与实际镜像，避免将运行时观察结果提升为权威状态。 */
export function reportMDeployRuntimeDrift(input: {
  readonly reportId: string
  readonly agentId: string
  readonly expectedDigest: MDeployDigestFromSchema
  readonly actualDigest: MDeployDigestFromSchema
  readonly timestamp: string
}): MDeployDriftReportV01FromSchema {
  const matches = digestKey(input.expectedDigest) === digestKey(input.actualDigest)
  return {
    schemaVersion: 'mdeploy.drift-report@0.1.0',
    reportId: input.reportId,
    agentId: input.agentId,
    expectedState: { digest: input.expectedDigest, source: 'git' },
    actualState: { digest: input.actualDigest, source: 'runtime' },
    driftType: 'artifact_digest',
    severity: matches ? 'low' : 'high',
    timestamp: input.timestamp,
    ...(matches ? { resolvedAt: input.timestamp } : {})
  }
}

function validateDesiredStateForRender(
  input: unknown,
  expectedRuntime: 'podman' | 'docker'
): Result<MDeployDesiredStateDocumentV01FromSchema, MDeployDriverError> {
  if (containsLiteralSecret(input)) {
    return err({
      code: 'literal_secret_rejected',
      message: 'secret-bearing desired-state fields must use SecretRef structures'
    })
  }
  const decoded = decodeMDeployDesiredStateDocumentV01(input)
  if (!decoded.ok) {
    return err({ code: 'desired_state_invalid', message: 'desired-state document is invalid' })
  }
  if (decoded.value.runtime.driver !== expectedRuntime) {
    return err({
      code: 'runtime_driver_mismatch',
      message: `desired-state runtime must be ${expectedRuntime} for this renderer`
    })
  }
  for (const service of decoded.value.services) {
    if (!isImmutableImage(service.image.image, service.image.digest)) {
      return err({
        code: 'mutable_image_reference',
        message: 'runtime manifests require an immutable canonical image digest'
      })
    }
  }
  return decoded
}

function isProductionValidationFixture(
  topology: MDeployInfrastructureTopologyV01FromSchema
): boolean {
  const counts = { 'control-state': 0, search: 0, leaf: 0 }
  const ids = new Set<string>()
  for (const node of topology.nodes) {
    counts[node.workloadClass]++
    if (node.runtimeDriver !== 'podman' || ids.has(node.nodeId)) return false
    if (
      node.nodeId.trim().length === 0 ||
      node.failureDomain.trim().length === 0 ||
      !positiveInteger(node.resources.vcpu) ||
      !positiveInteger(node.resources.memoryMiB) ||
      !positiveInteger(node.resources.diskGiB)
    ) {
      return false
    }
    ids.add(node.nodeId)
  }
  return counts['control-state'] === 3 && counts.search === 3 && counts.leaf === 2
}

function containsLiteralSecret(value: unknown, key = ''): boolean {
  if (Array.isArray(value)) return value.some(item => containsLiteralSecret(item))
  if (typeof value !== 'object' || value === null) return false
  if (isSecretRefConfig(value)) return !isSecretRef(Reflect.get(value, 'secretRef'))
  if (isSecretRef(value)) {
    const metadata = Reflect.get(value, 'metadata')
    return metadata === undefined ? false : containsLiteralSecret(metadata, 'metadata')
  }
  for (const [childKey, child] of Object.entries(value)) {
    if (isSecretBearingKey(childKey) && childKey !== 'secretRefs' && !isSecretRefConfig(child)) {
      return true
    }
    if (containsLiteralSecret(child, childKey)) return true
  }
  return isSecretBearingKey(key)
}

function renderQuadletService(
  service: MDeployDesiredStateDocumentV01FromSchema['services'][number]
): Result<MDeployRenderedFile, MDeployDriverError> {
  const serviceId = unitName(service.serviceId)
  if (!serviceId) {
    return err({ code: 'configuration_invalid', message: 'service id is not safe for a unit name' })
  }
  const container: string[] = [
    '[Unit]',
    `Description=Meristem ${serviceId} container`,
    '',
    '[Container]',
    `ContainerName=meristem-${serviceId}`,
    `Image=${digestImageReference(service.image.image, service.image.digest)}`,
    'Network=slirp4netns'
  ]
  for (const [key, config] of Object.entries(service.config).sort(([left], [right]) =>
    left.localeCompare(right)
  )) {
    if (!environmentName(key)) {
      return err({ code: 'configuration_invalid', message: 'service environment key is invalid' })
    }
    if (config.kind === 'plain') {
      const value = String(config.value)
      if (/[\n\r]/.test(value)) {
        return err({
          code: 'configuration_invalid',
          message: 'environment value contains a newline'
        })
      }
      container.push(`Environment=${key}=${systemdEscape(value)}`)
    } else {
      container.push(`Secret=${secretName(config.secretRef)},type=env,target=${key}`)
    }
  }
  container.push(
    '',
    '[Service]',
    'Restart=on-failure',
    '',
    '[Install]',
    'WantedBy=meristem.target',
    ''
  )
  return ok({ path: `${serviceId}.container`, content: container.join('\n') })
}

function renderMeristemTarget(desiredState: MDeployDesiredStateDocumentV01FromSchema): string {
  const wants = stableServices(desiredState)
    .map(service => unitName(service.serviceId))
    .filter((name): name is string => name !== null)
    .map(name => `${name}.service`)
    .join(' ')
  return [
    '[Unit]',
    'Description=Meristem rootless production runtime',
    `Wants=${wants}`,
    'After=network-online.target',
    '',
    '[Install]',
    'WantedBy=default.target',
    ''
  ].join('\n')
}

function renderComposeService(
  service: MDeployDesiredStateDocumentV01FromSchema['services'][number],
  externalSecrets: Map<string, string>
): Result<string, MDeployDriverError> {
  const serviceId = unitName(service.serviceId)
  if (!serviceId) {
    return err({ code: 'configuration_invalid', message: 'service id is not safe for Compose' })
  }
  const lines = [
    `  ${serviceId}:`,
    `    image: ${yamlQuote(digestImageReference(service.image.image, service.image.digest))}`,
    '    labels:',
    '      io.meristem.runtime-class: compatibility',
    '      io.meristem.compatibility-only: "true"'
  ]
  const environment: string[] = []
  const secrets: string[] = []
  for (const [key, config] of Object.entries(service.config).sort(([left], [right]) =>
    left.localeCompare(right)
  )) {
    if (!environmentName(key)) {
      return err({ code: 'configuration_invalid', message: 'service environment key is invalid' })
    }
    if (config.kind === 'plain') {
      const value = String(config.value)
      if (/[\n\r]/.test(value)) {
        return err({
          code: 'configuration_invalid',
          message: 'environment value contains a newline'
        })
      }
      environment.push(`      ${key}: ${yamlQuote(value)}`)
    } else {
      const name = secretName(config.secretRef)
      externalSecrets.set(name, secretExternalName(config.secretRef))
      secrets.push(`      - source: ${name}`, `        target: ${key}`)
    }
  }
  if (environment.length > 0) lines.push('    environment:', ...environment)
  if (secrets.length > 0) lines.push('    secrets:', ...secrets)
  return ok(lines.join('\n'))
}

function isSecretBearingKey(key: string): boolean {
  const normalized = key.toLowerCase()
  return secretBearingTerms.some(term => normalized.includes(term))
}

function isSecretRefConfig(value: unknown): boolean {
  return (
    typeof value === 'object' &&
    value !== null &&
    Reflect.get(value, 'kind') === 'secretRef' &&
    Reflect.has(value, 'secretRef')
  )
}

function isSecretRef(value: unknown): boolean {
  return (
    typeof value === 'object' &&
    value !== null &&
    typeof Reflect.get(value, 'provider') === 'string' &&
    typeof Reflect.get(value, 'keyPath') === 'string'
  )
}

function stableServices(desiredState: MDeployDesiredStateDocumentV01FromSchema) {
  return [...desiredState.services].sort((left, right) =>
    left.serviceId.localeCompare(right.serviceId)
  )
}

function positiveInteger(value: number): boolean {
  return Number.isInteger(value) && value > 0
}

function isImmutableImage(image: string, digest: MDeployDigestFromSchema): boolean {
  const expectedLength = digest.algorithm === 'sha256' ? 64 : 128
  const imageName = image.slice(image.lastIndexOf('/') + 1)
  return (
    image.trim() === image &&
    image.length > 0 &&
    !image.includes('@') &&
    !imageName.includes(':') &&
    digest.value.length === expectedLength &&
    /^[a-f0-9]+$/.test(digest.value)
  )
}

function digestImageReference(image: string, digest: MDeployDigestFromSchema): string {
  return `${image}@${digest.algorithm}:${digest.value}`
}

function unitName(value: string): string | null {
  return /^[a-z0-9][a-z0-9-]*$/.test(value) ? value : null
}

function environmentName(value: string): boolean {
  return /^[A-Z_][A-Z0-9_]*$/.test(value)
}

function secretName(ref: SecretIdentity): string {
  const base = `${ref.provider}-${ref.keyPath}`
    .toLowerCase()
    .replace(/[^a-z0-9_.-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 96)
  return ref.version === undefined ? base : `${base}-v${ref.version}`
}

function secretExternalName(ref: SecretIdentity): string {
  return `${ref.provider}:${ref.keyPath}${ref.version === undefined ? '' : `#${ref.version}`}`
}

function systemdEscape(value: string): string {
  return `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`
}

function yamlQuote(value: string): string {
  return JSON.stringify(value)
}

function digestKey(digest: MDeployDigestFromSchema): string {
  return `${digest.algorithm}:${digest.value}`
}
