export const activePublishedEventSubjects = [
  'audit.entry.created.v0',
  'core.lifecycle.degraded.v0',
  'core.lifecycle.started.v0',
  'extension.definition.registered.v0',
  'extension.definition.rejected.v0',
  'extension.instance.disable_failed.v0',
  'extension.instance.disabled.v0',
  'extension.instance.enable_failed.v0',
  'extension.instance.enabled.v0',
  'mnet.membership.joined.v0',
  'mnet.network.created.v0',
  'mnet.network_map.published.v0',
  'mnet.node_key.rotated.v0',
  'mnet.sidecar.lifecycle.v0',
  'mnet.sidecar.health.v0',
  'mnet.topology.update.v0',
  'mnet.migration.required.v0',
  'mnet.forced_relay.change.v0',
  'mnet.credential.expiry.v0',
  'mnet.profile.apply_failed.v0',
  'mnet.profile.defaults.updated.v0',
  'mnet.profile.disable.requested.v0',
  'mnet.profile.disabled.v0',
  'mnet.profile.enable.canceled.v0',
  'mnet.profile.enable.requested.v0',
  'mnet.profile.enabled.v0',
  'mnet.profile.defaults.updated.v0',
  'mnet.relay.assigned.v0',
  'node.join-ticket.created.v0',
  'node.registration.accepted.v0',
  'node.registration.requested.v0',
  'node.role.changed.v0',
  'node.status.changed.v0',
  'mnet.reachability.changed.v0',
  'policy.approval.approved.v0',
  'policy.approval.created.v0',
  'policy.approval.expired.v0',
  'policy.approval.rejected.v0',
  'policy.approval.vote.approved.v0',
  'policy.approval.vote.rejected.v0',
  'policy.decision.created.v0',
  'service.lifecycle.registered.v0',
  'service.lifecycle.reload.requested.v0',
  'task.canceled.v0',
  'task.completed.v0',
  'task.dispatched.v0',
  'task.failed.v0',
  'task.operation.rejected.v0',
  'task.operation.resume.failure.v0',
  'task.operation.resumed.v0',
  'task.operation.suspended.v0',
  'task.queued.v0',
  'task.requested.v0',
  'task.running.v0'
] as const

export const eventBusOperationalSubjects = [
  'meventbus.publish.rejected.v0',
  'meventbus.publish.failed.v0'
] as const

export const documentedEventBusSubjects = [
  'core.lifecycle.started.v0',
  'core.lifecycle.degraded.v0',
  'service.lifecycle.registered.v0',
  'service.lifecycle.reload.requested.v0',
  'service.lifecycle.reload.failed.v0',
  'node.registration.requested.v0',
  'node.registration.accepted.v0',
  'node.join-ticket.created.v0',
  'node.role.changed.v0',
  'node.status.changed.v0',
  'mnet.network.created.v0',
  'mnet.membership.joined.v0',
  'task.requested.v0',
  'task.queued.v0',
  'task.dispatched.v0',
  'task.running.v0',
  'task.completed.v0',
  'task.failed.v0',
  'task.cancel.requested.v0',
  'task.canceled.v0',
  'task.timed_out.v0',
  'task.retry.requested.v0',
  'task.retry.rejected.v0',
  'mnet.reachability.changed.v0',
  'mnet.path.changed.v0',
  'mnet.wstunnel.fallback.changed.v0',
  'mnet.network_map.published.v0',
  'mnet.node_key.rotated.v0',
  'mnet.relay.assigned.v0',
  'mnet.dataplane.tunnel.changed.v0',
  'mnet.sidecar.lifecycle.v0',
  'mnet.sidecar.health.v0',
  'mnet.topology.update.v0',
  'mnet.migration.required.v0',
  'mnet.forced_relay.change.v0',
  'mnet.credential.expiry.v0',
  'config.publish.requested.v0',
  'config.published.v0',
  'config.apply.acked.v0',
  'policy.decision.created.v0',
  'extension.definition.registered.v0',
  'extension.definition.rejected.v0',
  'extension.instance.enabled.v0',
  'extension.instance.disabled.v0',
  'extension.instance.enable_failed.v0',
  'extension.instance.disable_failed.v0',
  'identity.token.issued.v0',
  'identity.token.revoked.v0',
  'secret.ref.created.v0',
  'secret.ref.rotated.v0',
  'secret.ref.disabled.v0',
  'config.validated.v0',
  'config.apply.failed.v0',
  'config.rollback.requested.v0',
  'config.rolled_back.v0',
  'audit.lock.required.v0',
  'audit.entry.created.v0',
  'policy.approval.created.v0',
  'policy.approval.approved.v0',
  'policy.approval.rejected.v0',
  'policy.approval.expired.v0',
  'policy.approval.canceled.v0',
  'task.operation.suspended.v0',
  'task.operation.resumed.v0',
  'task.operation.resume.failure.v0',
  'task.operation.rejected.v0',
  'policy.approval.vote.approved.v0',
  'policy.approval.vote.rejected.v0',
  'mnet.profile.enable.requested.v0',
  'mnet.profile.enabled.v0',
  'mnet.profile.disable.requested.v0',
  'mnet.profile.disabled.v0',
  'mnet.profile.apply_failed.v0',
  'mnet.profile.enable.canceled.v0',
  'mnet.profile.defaults.updated.v0',
  'meventbus.publish.rejected.v0',
  'meventbus.publish.failed.v0'
] as const

export const allowedEventBusSubjects = documentedEventBusSubjects

export type AllowedEventBusSubject = (typeof allowedEventBusSubjects)[number]

export const allowedEventBusSubjectSet = new Set<string>(allowedEventBusSubjects)
