const repoRoot = import.meta.dir.replace(/\/scripts$/, '')
const composeSourcePath = `${repoRoot}/docker-compose.yml`
const outputDir = `${repoRoot}/ops/nixos/compose`
const generatedHeader = '# DO NOT EDIT - generated by scripts/generate-nix-compose.ts\n'

type ProfileName = 'base' | 'opensearch' | 'redis' | 'apisix'

type GenerationSpec = {
  outputName: string
  services: string[]
  runtimeArgs?: string[]
}

const generationSpecs: Record<ProfileName, GenerationSpec> = {
  base: { outputName: 'base.nix', services: ['postgres', 'nats'] },
  opensearch: { outputName: 'opensearch.nix', services: ['opensearch'] },
  redis: { outputName: 'redis.nix', services: ['redis'] },
  apisix: {
    outputName: 'apisix.nix',
    services: ['apisix'],
    runtimeArgs: ['--check_bind_mounts']
  }
}

const composeText = await Bun.file(composeSourcePath).text()

function sectionForService(serviceName: string): string {
  const startMarker = `  ${serviceName}:\n`
  const startIndex = composeText.indexOf(startMarker)
  if (startIndex === -1) {
    throw new Error(`Missing service ${serviceName} in docker-compose.yml`)
  }

  const remaining = composeText.slice(startIndex + startMarker.length)
  const nextMatch = remaining.match(/^ {2}[^\s].*:\n/m)
  const nextIndex = nextMatch?.index
  const endIndex =
    typeof nextIndex === 'number' ? startIndex + startMarker.length + nextIndex : composeText.length
  return composeText.slice(startIndex, endIndex).trimEnd()
}

function minimalComposeFor(services: string[]): string {
  const body = services
    .map(sectionForService)
    .map(section => section.replace(/\n {4}profiles:\n(?: {6}- .*\n)*/g, '\n'))
    .join('\n\n')
  return `services:\n${body}\n`
}

async function ensureOutputDir(): Promise<void> {
  await Bun.write(`${outputDir}/.keep`, '')
  await Bun.file(`${outputDir}/.keep`).delete()
}

function generatedPath(outputName: string): string {
  return `${outputDir}/${outputName}`
}

async function runCompose2Nix(profileName: ProfileName, spec: GenerationSpec): Promise<void> {
  const composePath = `/tmp/opencode/meristem-${profileName}.compose.yml`
  const rawOutputPath = `/tmp/opencode/meristem-${profileName}.generated.nix`

  await Bun.write(composePath, minimalComposeFor(spec.services))

  const result = Bun.spawnSync({
    cmd: [
      'compose2nix',
      '-project',
      'meristem',
      '-runtime',
      'docker',
      '-inputs',
      composePath,
      '-output',
      rawOutputPath,
      '-root_path',
      repoRoot,
      ...(spec.runtimeArgs ?? [])
    ],
    cwd: repoRoot,
    stdout: 'pipe',
    stderr: 'pipe'
  })

  if (result.exitCode !== 0) {
    throw new Error(`compose2nix failed for ${profileName}: ${result.stderr.toString()}`)
  }

  const rawText = await Bun.file(rawOutputPath).text()
  const normalizedText = normalizeGeneratedModule(profileName, rawText)
  await Bun.write(generatedPath(spec.outputName), generatedHeader + normalizedText)
}

function normalizeGeneratedModule(profileName: ProfileName, rawText: string): string {
  const workspacePath = repoRoot
  const workspacePlaceholder = '$' + '{workspaceDir}'
  let normalized = rawText.replace(`{ pkgs, lib, ... }`, `{ lib, pkgs, workspaceDir }`)
  normalized = normalized.replaceAll(workspacePath, workspacePlaceholder)
  normalized = normalized.replace(/^# Auto-generated by compose2nix\.\n\n/, '')
  normalized = normalized.replace(/\n{3,}/g, '\n\n')

  if (profileName !== 'base') {
    normalized = normalized
      .replace(
        /\n {2}# Runtime[\s\S]*?virtualisation\.oci-containers\.backend = "docker";\n\n/,
        '\n'
      )
      .replace(/\n {2}# Root service[\s\S]*?wantedBy = \[ "multi-user.target" \];\n {2}};\n/, '\n')
  }

  return `${normalized.trim()}\n`
}

async function main(): Promise<void> {
  await ensureOutputDir()

  for (const [profileName, spec] of Object.entries(generationSpecs) as Array<
    [ProfileName, GenerationSpec]
  >) {
    await runCompose2Nix(profileName, spec)
  }

  console.log('Generated compose2nix-derived Nix modules in ops/nixos/compose')
}

if (import.meta.main) {
  await main()
}
